In [29]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes. there is difference in the data type of variables list_ and array_list.

In [31]:
type(list_)

list

In [32]:
type(array_list)

numpy.ndarray

In [33]:
array_list.dtype

dtype('<U1')

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [22]:
for i in list_:
    print(i,type(i))


1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [23]:
for j in array_list:
    print(j,type(j))
    print(j,j.dtype)
    

1 <class 'numpy.str_'>
1 <U1
2 <class 'numpy.str_'>
2 <U1
3 <class 'numpy.str_'>
3 <U1
4 <class 'numpy.str_'>
4 <U1
5 <class 'numpy.str_'>
5 <U1


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [24]:
array_list = np.array(object = list_, dtype = int)

In [25]:
array_list

array([1, 2, 3, 4, 5])

In [27]:
array_list.dtype

dtype('int32')

yes.there will  be difference in data type in array_list.
and there will be no difference in list_ variable.

Consider the below code to answer further question.

In [35]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [36]:
num_array.shape

(2, 3)

In [37]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [38]:
arr_zeros=np.zeros((3,3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [43]:
arr_iden=np.identity(5)
arr_iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])